# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at the end of every day
    - cron: '0 0 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} curl -X POST -d {} https://api.netlify.com/build_hooks/5fc092b061324423a3f96465
